[colors]
primary = "#80d4da"
background = "#0e1415"
error = "#ffb4ab"
error_container = "#93000a"
inverse_on_surface = "#2b3232"
inverse_surface = "#dde4e4" 
on_background = "#dde4e4" 
on_error = "#690005"
on_error_container = "#ffdad6" 
on_primary = "#00373a" 
on_primary_container = "#9cf0f6" 
on_primary_fixed = "#002022" 
on_primary_fixed_variant = "#004f53"
on_secondary = "#1b3436" 
primary_container = "#004f53" 
secondary = "#b1cccd" 
surface_tint = "#80d4da" 
tertiary = "#b6c7ea" 
source_color = "#0c1a1b"
[mappings]
completion.category.bg = 'primary' 
completion.category.border.bottom = 'secondary'
completion.category.border.top = 'tertiary'
completion.category.fg= 'source_color'
completion.even.bg= 'inverse_on_surface'
completion.fg= 'error'
completion.item.selected.bg= 'surface_tint'
completion.item.selected.border.bottom= 'source_color' 
completion.item.selected.border.top= 'primary'
completion.item.selected.fg= 'secondary'
completion.item.selected.match.fg= 'on_secondary'
completion.match.fg= 'source_color'
completion.odd.bg= 'inverse_on_surface'
completion.scrollbar.bg='secondary'
completion.scrollbar.fg='tertiary'
contextmenu.disabled.bg= 'source_color'
contextmenu.disabled.fg= 'on_error' 
contextmenu.menu.bg= 'primary'
contextmenu.selected.bg= 'source_color'
contextmenu.selected.fg= 'background' 
# downloads.bar.bg=
# downloads.error.bg=
# downloads.error.fg=
# downloads.start.bg=
# download.start.fg=
# downloads.stop.fg=
# downloads.stop.bg=
# downloads.system.fg=
# downloads.system.bg=
# hints.bg=
# hints.fg=
# hints.match.fg=
# keyhint.bg=
# keyhint.fg=
# keyhint.suffix.fg=
# messages.error.bg=
# messages.error.border=
# messages.error.fg= 
# messages.info.bg=
# messages.info.border=
# messages.info.fg=
# messages.warning.bg=
# messages.warning.border=
# messages.warning.fg=
# prompts.bg=
# prompts.border=
# prompts.fg=
# prompts.selected.fg=
# prompts.selected.bg=
# statusbar.caret.selection.bg=
# statusbar.caret.selection.fg=
# statusbar.command.bg=
# statusbar.command.fg=
# statusbar.comand.private.bg=
# statusbar.command.private.fg=
# statusbar.normal.fg=
# statusbar.normal.fg=
# statusbar.passthrough.bg=
# statusbar.passthrough.fg=
# statusbar.private.bg=
# statusbar.private.fg=
# statusbar.progress.bg=
# statusbar.url.error.fg=
# statusbar.url.fg=
# statusbar.url.sucess.http.fg=
# statusbar.url.sucess.http.bg=
# statusbar.url.warn.fg=
tabs.bar.bg= 'primary'
tabs.even.bg= 'secondary'
tabs.even.fg= 'tertiary'
tabs.odd.bg= 'source_color'
# tabs.odd.fg= primary
# tabs.indicator.start=
# tabs.indicator.error=
# tabs.indicator.stop=
# tabs.indicator.system=
# tabs.pinned.even.bg=
# tabs.pinned.even.fg=
# tabs.pinned.odd.bg=
# tabs.pinned.odd.fg=
# tabs.pinned.selected.even.bg=
# tabs.pinned.selected.even.fg=
# tabs.pinned.selected.odd.bg=
# tabs.pinned.selected.odd.fg=
# tabs.selected.even.bg=
# tabs.selected.even.fg=
# tabs.selected.odd.bg=
# tabs.selected.odd.fg=
# tooltip.bg=
# tooltip.fg=
# webpage.bg=

