[FileDialog]
history=file:///home/ascaletty23/Downloads/Uganda, file:///home/ascaletty23/Uganda, file:///home/ascaletty23/Downloads/UgandatoUpload, file:///home/ascaletty23/Uganda/Uganda ToShare/post_trip_report_attachments/D PMEL Data/D.1 Head Count Collection, file:///home/ascaletty23/Downloads
lastVisited=file:///home/ascaletty23/Downloads/UgandatoUpload
qtVersion=6.9.1
shortcuts=file:, file:///home/ascaletty23
sidebarWidth=95
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)"
viewMode=Detail
