[FileDialog]
history=file:///home/ascaletty23/projects/rust/statics/truss/test_trusses, file:///home/ascaletty23, file:///home/ascaletty23/Uganda/GPSDATA/GPS Data, file:///home/ascaletty23/projects/qmk_firmware/keyboards/ferris/keymaps, file:///home/ascaletty23/projects/qmk_firmware, file:///home/ascaletty23/Downloads
lastVisited=file:///home/ascaletty23/Downloads
qtVersion=6.10.0
shortcuts=file:, file:///home/ascaletty23
sidebarWidth=95
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)"
viewMode=Detail
