[colors]
primary = "{{colors.primary.default.hex}}"
background = "{{colors.background.default.hex}}"
error = "{{colors.error.default.hex}}"
error_container = "{{colors.error_container.default.hex}}"
inverse_on_surface = "{{colors.inverse_on_surface.default.hex}}"
inverse_surface = "{{colors.inverse_surface.default.hex}}" 
on_background = "{{colors.on_background.default.hex}}" 
on_error = "{{colors.on_error.default.hex}}"
on_error_container = "{{colors.on_error_container.default.hex}}" 
on_primary = "{{colors.on_primary.default.hex}}" 
on_primary_container = "{{colors.on_primary_container.default.hex}}" 
on_primary_fixed = "{{colors.on_primary_fixed.default.hex}}" 
on_primary_fixed_variant = "{{colors.on_primary_fixed_variant.default.hex}}"
on_secondary = "{{colors.on_secondary.default.hex}}" 
primary_container = "{{colors.primary_container.default.hex}}" 
secondary = "{{colors.secondary.default.hex}}" 
surface_tint = "{{colors.surface_tint.default.hex}}" 
tertiary = "{{colors.tertiary.default.hex}}" 
source_color = "{{colors.source_color.default.hex}}"
[mappings]
completion.category.bg = 'primary' 
completion.category.border.bottom = 'secondary'
completion.category.border.top = 'tertiary'
completion.category.fg= 'source_color'
completion.even.bg= 'inverse_on_surface'
completion.fg= 'error'
completion.item.selected.bg= 'surface_tint'
completion.item.selected.border.bottom= 'source_color' 
completion.item.selected.border.top= 'primary'
completion.item.selected.fg= 'secondary'
completion.item.selected.match.fg= 'on_secondary'
completion.match.fg= 'source_color'
completion.odd.bg= 'inverse_on_surface'
completion.scrollbar.bg='secondary'
completion.scrollbar.fg='tertiary'
contextmenu.disabled.bg= 'source_color'
contextmenu.disabled.fg= 'on_error' 
contextmenu.menu.bg= 'primary'
contextmenu.selected.bg= 'source_color'
contextmenu.selected.fg= 'background' 
# downloads.bar.bg=
# downloads.error.bg=
# downloads.error.fg=
# downloads.start.bg=
# download.start.fg=
# downloads.stop.fg=
# downloads.stop.bg=
# downloads.system.fg=
# downloads.system.bg=
# hints.bg=
# hints.fg=
# hints.match.fg=
# keyhint.bg=
# keyhint.fg=
# keyhint.suffix.fg=
# messages.error.bg=
# messages.error.border=
# messages.error.fg= 
# messages.info.bg=
# messages.info.border=
# messages.info.fg=
# messages.warning.bg=
# messages.warning.border=
# messages.warning.fg=
# prompts.bg=
# prompts.border=
# prompts.fg=
# prompts.selected.fg=
# prompts.selected.bg=
# statusbar.caret.selection.bg=
# statusbar.caret.selection.fg=
# statusbar.command.bg=
# statusbar.command.fg=
# statusbar.comand.private.bg=
# statusbar.command.private.fg=
# statusbar.normal.fg=
# statusbar.normal.fg=
# statusbar.passthrough.bg=
# statusbar.passthrough.fg=
# statusbar.private.bg=
# statusbar.private.fg=
# statusbar.progress.bg=
# statusbar.url.error.fg=
# statusbar.url.fg=
# statusbar.url.sucess.http.fg=
# statusbar.url.sucess.http.bg=
# statusbar.url.warn.fg=
tabs.bar.bg= 'primary'
tabs.even.bg= 'secondary'
tabs.even.fg= 'tertiary'
tabs.odd.bg= 'source_color'
# tabs.odd.fg= primary
# tabs.indicator.start=
# tabs.indicator.error=
# tabs.indicator.stop=
# tabs.indicator.system=
# tabs.pinned.even.bg=
# tabs.pinned.even.fg=
# tabs.pinned.odd.bg=
# tabs.pinned.odd.fg=
# tabs.pinned.selected.even.bg=
# tabs.pinned.selected.even.fg=
# tabs.pinned.selected.odd.bg=
# tabs.pinned.selected.odd.fg=
# tabs.selected.even.bg=
# tabs.selected.even.fg=
# tabs.selected.odd.bg=
# tabs.selected.odd.fg=
# tooltip.bg=
# tooltip.fg=
# webpage.bg=

