
$image = wallpapers/forest
$background = rgba(101418ff)

$image = wallpapers/forest
$error = rgba(ffb4abff)

$image = wallpapers/forest
$error_container = rgba(93000aff)

$image = wallpapers/forest
$inverse_on_surface = rgba(2d3135ff)

$image = wallpapers/forest
$inverse_primary = rgba(2d638bff)

$image = wallpapers/forest
$inverse_surface = rgba(e0e2e8ff)

$image = wallpapers/forest
$on_background = rgba(e0e2e8ff)

$image = wallpapers/forest
$on_error = rgba(690005ff)

$image = wallpapers/forest
$on_error_container = rgba(ffdad6ff)

$image = wallpapers/forest
$on_primary = rgba(003352ff)

$image = wallpapers/forest
$on_primary_container = rgba(cde5ffff)

$image = wallpapers/forest
$on_primary_fixed = rgba(001d32ff)

$image = wallpapers/forest
$on_primary_fixed_variant = rgba(094b72ff)

$image = wallpapers/forest
$on_secondary = rgba(233240ff)

$image = wallpapers/forest
$on_secondary_container = rgba(d4e4f6ff)

$image = wallpapers/forest
$on_secondary_fixed = rgba(0d1d2aff)

$image = wallpapers/forest
$on_secondary_fixed_variant = rgba(394857ff)

$image = wallpapers/forest
$on_surface = rgba(e0e2e8ff)

$image = wallpapers/forest
$on_surface_variant = rgba(c2c7ceff)

$image = wallpapers/forest
$on_tertiary = rgba(382a4aff)

$image = wallpapers/forest
$on_tertiary_container = rgba(eddcffff)

$image = wallpapers/forest
$on_tertiary_fixed = rgba(221533ff)

$image = wallpapers/forest
$on_tertiary_fixed_variant = rgba(4f4061ff)

$image = wallpapers/forest
$outline = rgba(8c9198ff)

$image = wallpapers/forest
$outline_variant = rgba(42474eff)

$image = wallpapers/forest
$primary = rgba(99ccfaff)

$image = wallpapers/forest
$primary_container = rgba(094b72ff)

$image = wallpapers/forest
$primary_fixed = rgba(cde5ffff)

$image = wallpapers/forest
$primary_fixed_dim = rgba(99ccfaff)

$image = wallpapers/forest
$scrim = rgba(000000ff)

$image = wallpapers/forest
$secondary = rgba(b8c8daff)

$image = wallpapers/forest
$secondary_container = rgba(394857ff)

$image = wallpapers/forest
$secondary_fixed = rgba(d4e4f6ff)

$image = wallpapers/forest
$secondary_fixed_dim = rgba(b8c8daff)

$image = wallpapers/forest
$shadow = rgba(000000ff)

$image = wallpapers/forest
$source_color = rgba(0a4c74ff)

$image = wallpapers/forest
$surface = rgba(101418ff)

$image = wallpapers/forest
$surface_bright = rgba(36393eff)

$image = wallpapers/forest
$surface_container = rgba(1c2024ff)

$image = wallpapers/forest
$surface_container_high = rgba(272a2eff)

$image = wallpapers/forest
$surface_container_highest = rgba(313539ff)

$image = wallpapers/forest
$surface_container_low = rgba(181c20ff)

$image = wallpapers/forest
$surface_container_lowest = rgba(0b0f12ff)

$image = wallpapers/forest
$surface_dim = rgba(101418ff)

$image = wallpapers/forest
$surface_tint = rgba(99ccfaff)

$image = wallpapers/forest
$surface_variant = rgba(42474eff)

$image = wallpapers/forest
$tertiary = rgba(d2bfe7ff)

$image = wallpapers/forest
$tertiary_container = rgba(4f4061ff)

$image = wallpapers/forest
$tertiary_fixed = rgba(eddcffff)

$image = wallpapers/forest
$tertiary_fixed_dim = rgba(d2bfe7ff)

